# Generated by Django 4.2.25 on 2025-10-06 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('duration_days', models.IntegerField(verbose_name='مدت (روز)')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('currency', models.CharField(default='IRR', max_length=10, verbose_name='واحد پول')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش')),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('card_num', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='شناسه درخواست (id_get)')),
                ('factor_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره فاکتور')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('successful', 'موفق'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payment_tra_status_deda57_idx'), models.Index(fields=['user'], name='payment_tra_user_id_b01674_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('currency', models.CharField(default='IRR', max_length=10, verbose_name='واحد پول')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('SUCCESS', 'موفق'), ('FAILED', 'ناموفق')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('before_end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا قبل')),
                ('after_end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا بعد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.subscriptionplan', verbose_name='پلن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش اشتراک',
                'verbose_name_plural': 'تراکنش\u200cهای اشتراک',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payment_sub_user_id_ea8b74_idx'), models.Index(fields=['status', 'created_at'], name='payment_sub_status_a2c1f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payment.subscriptionplan', verbose_name='پلن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک',
                'verbose_name_plural': 'اشتراک\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'end_date'], name='payment_sub_user_id_48936a_idx')],
            },
        ),
    ]
